"""Initial_migration

Revision ID: 899d1db911e6
Revises: 
Create Date: 2026-01-10 00:36:18.040537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '899d1db911e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('bankroll', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_played', sa.DateTime(timezone=True), nullable=False),
    sa.Column('skill_level', sa.String(length=32), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=False),
    sa.Column('game_type', sa.String(length=32), nullable=False),
    sa.Column('limit_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buy_in', sa.Integer(), nullable=False),
    sa.Column('cash_out', sa.Integer(), nullable=True),
    sa.Column('hands_played', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['player_name'], ['players.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_player_name'), 'game_sessions', ['player_name'], unique=False)
    op.create_table('hands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('player_name', sa.String(length=64), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hole_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('board_cards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('winner', sa.String(length=64), nullable=True),
    sa.Column('winning_hand_rank', sa.String(length=32), nullable=True),
    sa.Column('pot_size', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['player_name'], ['players.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hands_player_name'), 'hands', ['player_name'], unique=False)
    op.create_index(op.f('ix_hands_session_id'), 'hands', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hands_session_id'), table_name='hands')
    op.drop_index(op.f('ix_hands_player_name'), table_name='hands')
    op.drop_table('hands')
    op.drop_index(op.f('ix_game_sessions_player_name'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('players')
    # ### end Alembic commands ###
